// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIP) DeepCopyInto(out *RoutedIP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIP.
func (in *RoutedIP) DeepCopy() *RoutedIP {
	if in == nil {
		return nil
	}
	out := new(RoutedIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoutedIP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIPList) DeepCopyInto(out *RoutedIPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoutedIP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIPList.
func (in *RoutedIPList) DeepCopy() *RoutedIPList {
	if in == nil {
		return nil
	}
	out := new(RoutedIPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoutedIPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIPSpec) DeepCopyInto(out *RoutedIPSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIPSpec.
func (in *RoutedIPSpec) DeepCopy() *RoutedIPSpec {
	if in == nil {
		return nil
	}
	out := new(RoutedIPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIPStatus) DeepCopyInto(out *RoutedIPStatus) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIPStatus.
func (in *RoutedIPStatus) DeepCopy() *RoutedIPStatus {
	if in == nil {
		return nil
	}
	out := new(RoutedIPStatus)
	in.DeepCopyInto(out)
	return out
}
