// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/routedip/v1alpha1.RoutedIP":       schema_pkg_apis_routedip_v1alpha1_RoutedIP(ref),
		"./pkg/apis/routedip/v1alpha1.RoutedIPSpec":   schema_pkg_apis_routedip_v1alpha1_RoutedIPSpec(ref),
		"./pkg/apis/routedip/v1alpha1.RoutedIPStatus": schema_pkg_apis_routedip_v1alpha1_RoutedIPStatus(ref),
	}
}

func schema_pkg_apis_routedip_v1alpha1_RoutedIP(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RoutedIP is the Schema for the routedips API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/routedip/v1alpha1.RoutedIPSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/routedip/v1alpha1.RoutedIPStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/routedip/v1alpha1.RoutedIPSpec", "./pkg/apis/routedip/v1alpha1.RoutedIPStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_routedip_v1alpha1_RoutedIPSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RoutedIPSpec defines the desired state of RoutedIP",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_routedip_v1alpha1_RoutedIPStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RoutedIPStatus defines the observed state of RoutedIP",
				Type:        []string{"object"},
			},
		},
	}
}
