// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuer":       schema_pkg_apis_routedipoperator_v1alpha1_ClusterRoutedIPIssuer(ref),
		"./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuerSpec":   schema_pkg_apis_routedipoperator_v1alpha1_ClusterRoutedIPIssuerSpec(ref),
		"./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuerStatus": schema_pkg_apis_routedipoperator_v1alpha1_ClusterRoutedIPIssuerStatus(ref),
		"./pkg/apis/routedipoperator/v1alpha1.RoutedIP":                    schema_pkg_apis_routedipoperator_v1alpha1_RoutedIP(ref),
		"./pkg/apis/routedipoperator/v1alpha1.RoutedIPSpec":                schema_pkg_apis_routedipoperator_v1alpha1_RoutedIPSpec(ref),
		"./pkg/apis/routedipoperator/v1alpha1.RoutedIPStatus":              schema_pkg_apis_routedipoperator_v1alpha1_RoutedIPStatus(ref),
	}
}

func schema_pkg_apis_routedipoperator_v1alpha1_ClusterRoutedIPIssuer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClusterRoutedIPIssuer is the Schema for the clusterroutedipissuers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuerSpec", "./pkg/apis/routedipoperator/v1alpha1.ClusterRoutedIPIssuerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_routedipoperator_v1alpha1_ClusterRoutedIPIssuerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClusterRoutedIPIssuerSpec defines the desired state of ClusterRoutedIPIssuer",
				Properties: map[string]spec.Schema{
					"className": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"firewallPostAllow": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"boolean"},
							Format: "",
						},
					},
					"nodePortRange": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"perNodeIPLimit": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"integer"},
							Format: "int32",
						},
					},
					"fromSecretsRef": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"updateRoutedIPSpec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/kubernetes/pkg/apis/batch.JobSpec"),
						},
					},
					"updateFirewallSpec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/kubernetes/pkg/apis/batch.JobSpec"),
						},
					},
				},
				Required: []string{"className", "firewallPostAllow", "nodePortRange", "perNodeIPLimit", "fromSecretsRef", "updateRoutedIPSpec", "updateFirewallSpec"},
			},
		},
		Dependencies: []string{
			"k8s.io/kubernetes/pkg/apis/batch.JobSpec"},
	}
}

func schema_pkg_apis_routedipoperator_v1alpha1_ClusterRoutedIPIssuerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClusterRoutedIPIssuerStatus defines the observed state of ClusterRoutedIPIssuer",
				Properties: map[string]spec.Schema{
					"routedIPs": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html RoutedIPs is a list of the RoutedIP names",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("k8s.io/apimachinery/pkg/types.NamespacedName"),
									},
								},
							},
						},
					},
				},
				Required: []string{"routedIPs"},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/types.NamespacedName"},
	}
}

func schema_pkg_apis_routedipoperator_v1alpha1_RoutedIP(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RoutedIP is the Schema for the routedips API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/routedipoperator/v1alpha1.RoutedIPSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/routedipoperator/v1alpha1.RoutedIPStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/routedipoperator/v1alpha1.RoutedIPSpec", "./pkg/apis/routedipoperator/v1alpha1.RoutedIPStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_routedipoperator_v1alpha1_RoutedIPSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RoutedIPSpec defines the desired state of RoutedIP",
				Properties: map[string]spec.Schema{
					"className": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"routedIP": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"serviceRef": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/types.NamespacedName"),
						},
					},
				},
				Required: []string{"className", "routedIP", "serviceRef"},
			},
		},
		Dependencies: []string{
			"k8s.io/apimachinery/pkg/types.NamespacedName"},
	}
}

func schema_pkg_apis_routedipoperator_v1alpha1_RoutedIPStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RoutedIPStatus defines the observed state of RoutedIP",
				Properties: map[string]spec.Schema{
					"assignedNode": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"assignedNode"},
			},
		},
		Dependencies: []string{},
	}
}
