// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoutedIPIssuer) DeepCopyInto(out *ClusterRoutedIPIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoutedIPIssuer.
func (in *ClusterRoutedIPIssuer) DeepCopy() *ClusterRoutedIPIssuer {
	if in == nil {
		return nil
	}
	out := new(ClusterRoutedIPIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRoutedIPIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoutedIPIssuerList) DeepCopyInto(out *ClusterRoutedIPIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRoutedIPIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoutedIPIssuerList.
func (in *ClusterRoutedIPIssuerList) DeepCopy() *ClusterRoutedIPIssuerList {
	if in == nil {
		return nil
	}
	out := new(ClusterRoutedIPIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRoutedIPIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoutedIPIssuerSpec) DeepCopyInto(out *ClusterRoutedIPIssuerSpec) {
	*out = *in
	in.UpdateRoutedIPSpec.DeepCopyInto(&out.UpdateRoutedIPSpec)
	in.UpdateFirewallSpec.DeepCopyInto(&out.UpdateFirewallSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoutedIPIssuerSpec.
func (in *ClusterRoutedIPIssuerSpec) DeepCopy() *ClusterRoutedIPIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRoutedIPIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRoutedIPIssuerStatus) DeepCopyInto(out *ClusterRoutedIPIssuerStatus) {
	*out = *in
	if in.RoutedIPs != nil {
		in, out := &in.RoutedIPs, &out.RoutedIPs
		*out = make([]types.NamespacedName, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRoutedIPIssuerStatus.
func (in *ClusterRoutedIPIssuerStatus) DeepCopy() *ClusterRoutedIPIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRoutedIPIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIP) DeepCopyInto(out *RoutedIP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIP.
func (in *RoutedIP) DeepCopy() *RoutedIP {
	if in == nil {
		return nil
	}
	out := new(RoutedIP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoutedIP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIPList) DeepCopyInto(out *RoutedIPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RoutedIP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIPList.
func (in *RoutedIPList) DeepCopy() *RoutedIPList {
	if in == nil {
		return nil
	}
	out := new(RoutedIPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RoutedIPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIPSpec) DeepCopyInto(out *RoutedIPSpec) {
	*out = *in
	out.ServiceRef = in.ServiceRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIPSpec.
func (in *RoutedIPSpec) DeepCopy() *RoutedIPSpec {
	if in == nil {
		return nil
	}
	out := new(RoutedIPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutedIPStatus) DeepCopyInto(out *RoutedIPStatus) {
	*out = *in
	if in.AssignedNode != nil {
		in, out := &in.AssignedNode, &out.AssignedNode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutedIPStatus.
func (in *RoutedIPStatus) DeepCopy() *RoutedIPStatus {
	if in == nil {
		return nil
	}
	out := new(RoutedIPStatus)
	in.DeepCopyInto(out)
	return out
}
